### ISSUE TITLE
In 1.1, should OSMF and SOTM be limited to the geodata context?

### ISSUE THREAD

**Issue by tieguy** [tieguy/collabmark.org#24]
Compare to OSM, which says it is "limited to the geodata context".

**Comment by tieguy** [comment]
Simon says that in the OSM case, this was "just a bit of hedging". Unclear to Luis if we should do the same hedging in other contexts.

**Comment by simonpoole** [comment]
I don't really have a strong feeling. Three and four letter abbreviations are in general hopeless in that they collide with lots of other uses and OSM, OSMF and SOTM are no different in that respect. I would probably drop the "geodata context" completely.

**Comment by tieguy** [comment]
I do think the "geodata context" has some value - shows the OSM community that OSMF is being reasonable and not overreaching. But does add complexity, so really up to OSMF.

**Comment by woodpeck** [comment]
I agree that it is confusing when some marks are limited to the geodata context and others not. I wanted to suggest to scrap the limitation and replace it with a general sentence at the end: "These marks are covered by this policy only where used in a geodata or OpenStreetMap context." - but then we don't anyone to sell OpenStreetMap branded chocolate bars. 

Not to appear overreaching is a good goal. Can we re-order the list so that OSMF, SotM and OSM appear last, and interject "The following abbreviations are covered by this policy only when used in the OpenStreetMap or geodata context"?

**Comment by tieguy** [comment]
Based a solution on @woodpeck 's suggestion.
