### ISSUE TITLE
4.3 reference to US law

### ISSUE THREAD

**Issue by simonpoole** [tieguy/collabmark.org#26]
While not wrong, it seems a bit weird for a UK org to refer to "U.S. trademark law or other applicable foreign laws"

**Comment by tieguy** [comment]
Fair point! Where (if anywhere) do we have registrations?

**Comment by tieguy** [comment]
I've created an [upstream pull request](https://github.com/collabmark/collabmark.org/pull/38) to fix this in the template, but will wait to fix it here until I understand the state of OSM's registrations better, since it may make sense for OSM to refer to UK and/or US law even if that doesn't make sense for the template.

**Comment by simonpoole** [comment]
There's a better list somewhere and an excel spreadsheet from me (need to dig both out, update: spreadsheet sent by mail), but https://wiki.openstreetmap.org/wiki/Trademark has the relevant information a bit spread out.

**Comment by tieguy** [comment]
Thanks, Simon. Given that marks are filed in the US, UK, and EU, I think the right approach is to simply say "relevant law" and tweak the language to also refer to the similar EU concept of "referential" use. Will do that momentarily.
