### ISSUE TITLE
Registered trademark

### ISSUE THREAD

**Issue by pnorman** [tieguy/collabmark.org#30]
> If the mark will primarily appear on a mobile screen or another medium with limited visual space, you may instead use a trademark symbol (™)

Should this instead be a registered trademark symbol?

**Comment by tieguy** [comment]
Depends. At least some countries strongly disapprove of using the (r) when you're not actually registered in that country, while using the (tm) instead of (r) is not damaging.

Could say "trademark (tm) or registered trademark (r) symbols, as appropriate", but that's going to introduce additional confusion.
